import { IQuestion } from '@/types'

const questions: IQuestion[] = [
  { index: 1, type: 4, value: null, question: '나는 감성적이어서 혼자 있을 때가 많다.' },
  { index: 2, type: 2, value: null, question: '나는 다른 사람들과 함께 일하기를 더 좋아한다.' },
  { index: 3, type: 4, value: null, question: '나는 혼자서 자신만의 고상한 취미를 즐긴다.' },
  { index: 4, type: 2, value: null, question: '나는 무슨 일이 있어도 사람들과 한 약속은 잘 지킨다.' },
  { index: 5, type: 3, value: null, question: '나는 능력을 발휘하는 데 많은 시간을 투자한다.' },
  { index: 6, type: 4, value: null, question: '나는 낭만적이고 예술가적인 기질이 있다.' },
  { index: 7, type: 2, value: null, question: '나는 사람들에게 칭찬을 잘 한다.' },
  { index: 8, type: 2, value: null, question: '내 생각보다는 남의 생각에 공감할 때가 많다.' },
  { index: 9, type: 3, value: null, question: '나는 과정보다는 결과를 중시한다.' },
  { index: 10, type: 3, value: null, question: '나는 인간중심적이기보다는 오히려 목표 중심적이다.' },
  { index: 11, type: 4, value: null, question: '나는 어떤 상황에서 이방인처럼 느껴질 때가 많다.' },
  { index: 12, type: 3, value: null, question: '나는 적응력이 뛰어나 상황에 적절히 대응한다.' },
  { index: 13, type: 4, value: null, question: '나는 다른 사람들과는 다른 독특한 감정을 가지고 있다.' },
  { index: 14, type: 4, value: null, question: '나는 주변 분위기에 약하고 자기 생각에 골몰하는 편이다.' },
  { index: 15, type: 3, value: null, question: '나는 사람들에게 지나친 경쟁을 강요한다.' },
  { index: 16, type: 2, value: null, question: '나는 친구들이 나에게 의지할 때 기분이 좋다.' },
  { index: 17, type: 3, value: null, question: '나는 사람들에 대한 배려보다는 일의 성취를 중요하게 생각한다.' },
  { index: 18, type: 2, value: null, question: '나는 사람들을 관심 있게 대하고 보살피려 한다.' },
  { index: 19, type: 2, value: null, question: '나는 사람들과 친해지려고 많이 노력하고 있다.' },
  { index: 20, type: 4, value: null, question: '나는 내 행동의 동기와 감정에 대해 회의스런 생각이 들 때가 있다.' },
  { index: 21, type: 3, value: null, question: '나는 성공만이 애정을 획득할 수 있다고 믿는다.' },
  { index: 22, type: 3, value: null, question: '나는 실패를 두려워하여 과장하는 경향이 있다.' },
  { index: 23, type: 2, value: null, question: '나는 타인의 만족을 위해 노력한다.' },
  { index: 24, type: 4, value: null, question: '나는 감동적인 것을 추구하다가 혼자 우울해지기도 한다.' },
  { index: 25, type: 2, value: null, question: '나는 타인의 호감을 얻기 위해 노력한다.' },
  { index: 26, type: 3, value: null, question: '나는 침체에 빠지지 않고 무엇인가를 끊임없이 행한다.' },
  { index: 27, type: 4, value: null, question: '나는 비현실적이며 몽상가적 기질을 가지고 있다.' },
  { index: 28, type: 5, value: null, question: '나는 무엇인가에 대하여 집중하여 통찰한다.' },
  { index: 29, type: 7, value: null, question: '나는 자발적으로 재미있는 일을 즐긴다.' },
  { index: 30, type: 5, value: null, question: '나는 문제가 있으면 풀릴 때까지 그것만 골똘히 생각한다.' },
  { index: 31, type: 5, value: null, question: '나는 공적인 것보다는 개인 생활에 대한 관심이 많다.' },
  { index: 32, type: 7, value: null, question: '나는 모험적이며 위험을 감수한다.' },
  { index: 33, type: 7, value: null, question: '나는 끊임없이 변화하는 생활을 좋아한다.' },
  { index: 34, type: 6, value: null, question: '나는 명확한 지침이 있을 때 일의 능률이 오른다.' },
  { index: 35, type: 6, value: null, question: '나는 사랑하는 사람을 가끔 의심하는 경향이 있다.' },
  { index: 36, type: 7, value: null, question: '나는 자극과 흥분을 유발하는 활동을 좋아한다.' },
  { index: 37, type: 5, value: null, question: '나는 감정보다는 이성을 추구한다.' },
  { index: 38, type: 7, value: null, question: '나는 어린아이처럼 명랑하고 순진하다.' },
  { index: 39, type: 6, value: null, question: '나의 성공에 대해서도 가끔 평가절하하는 경향이 있다.' },
  { index: 40, type: 5, value: null, question: '나는 시간이나 돈을 아끼는 경향이 있다.' },
  { index: 41, type: 6, value: null, question: '나는 잘 훈련되어 있어 조직이나 집단에 헌신할 수 있다.' },
  { index: 42, type: 5, value: null, question: '나의 관심사는 나를 둘러싼 세계를 이해하는 것이다.' },
  { index: 43, type: 6, value: null, question: '나는 모든 일에서 안전을 중요하게 생각한다.' },
  { index: 44, type: 5, value: null, question: '나는 권위를 믿지 않고 규칙을 무시한다.' },
  { index: 45, type: 7, value: null, question: '나는 미래에 대해 항상 열정을 가지고 있다.' },
  { index: 46, type: 6, value: null, question: '사람들은 때로 내게 용기가 필요하다고 말한다.' },
  { index: 47, type: 7, value: null, question: '나는 여러 가지 일들을 즐기며 새로운 경험을 갈망한다.' },
  { index: 48, type: 7, value: null, question: '나는 한 가지 일에 정착하기 어렵다.' },
  { index: 49, type: 5, value: null, question: '나는 지적이고 냉철하게 관찰하는 편이다.' },
  { index: 50, type: 6, value: null, question: '나는 결과에 대한 두려움 때문에 일을 질질 끄는 경우가 있다.' },
  { index: 51, type: 5, value: null, question: '나는 머리로 모든 것을 이해하고 판단한다.' },
  { index: 52, type: 6, value: null, question: '나는 충성할 만한 사람이라고 판단되면 헌신할 수 있다.' },
  { index: 53, type: 7, value: null, question: '나는 현실에 만족하지 않고 새로운 것을 추구한다.' },
  { index: 54, type: 6, value: null, question: '나는 친하게 지내는 사람과 영원한 우정을 유지하도록 노력한다.' },
  { index: 55, type: 9, value: null, question: '나는 자기만족적이며 태평한 편이다.' },
  { index: 56, type: 1, value: null, question: '나는 모든 일을 개선하기 위해 깊이 생각해서 행동한다.' },
  { index: 57, type: 8, value: null, question: '나에게는 지도자로서의 기질이 있다.' },
  { index: 58, type: 8, value: null, question: '나는 의사 결정을 할 때 적절히 지도력을 발휘한다.' },
  { index: 59, type: 9, value: null, question: '나는 감정 동요가 많지 않은 원만한 사람이다.' },
  { index: 60, type: 9, value: null, question: '나는 안전한 해결력을 원하고 되도록 갈등을 피한다.' },
  { index: 61, type: 9, value: null, question: '나는 친구들과 긴장을 풀고 마음 편하게 지낸다.' },
  { index: 62, type: 1, value: null, question: '나는 다른 사람들보다 근면하며 책임감이 강하다.' },
  { index: 63, type: 8, value: null, question: '나는 늘 강해야 된다고 생각한다.' },
  { index: 64, type: 1, value: null, question: '나는 정직하고 자제력이 있는 사람이다.' },
  { index: 65, type: 9, value: null, question: '나는 사람들을 유쾌하고 편하게 대한다.' },
  { index: 66, type: 1, value: null, question: '나의 행동은 원칙에 기초를 둔다.' },
  { index: 67, type: 1, value: null, question: '나는 완벽을 위해 끝까지 참고 노력한다.' },
  { index: 68, type: 8, value: null, question: '나는 사람들에게 영향력 있는 사람이다.' },
  { index: 69, type: 8, value: null, question: '나는 다른 사람들이 말하기 어려워하는 것을 이야기한다.' },
  { index: 70, type: 8, value: null, question: '나는 공격적이고 자기주장이 강하다.' },
  { index: 71, type: 8, value: null, question: '나는 사람들을 통제하려 한다.' },
  { index: 72, type: 9, value: null, question: '사람들은 나를 그냥 좋아한다.' },
  { index: 73, type: 8, value: null, question: '나는 사람들을 지시하고 동기를 부여한다.' },
  { index: 74, type: 1, value: null, question: '나는 규칙을 잘 지키며 엄격하다.' },
  { index: 75, type: 9, value: null, question: '나는 세상에 대해 낙관적인 편이다.' },
  { index: 76, type: 8, value: null, question: '나는 강한 자신감으로 사람들을 설득시킨다.' },
  { index: 77, type: 1, value: null, question: '나는 다른 사람들의 신임을 얻을 수 있다.' },
  { index: 78, type: 9, value: null, question: '사람들이 하는 일은 각자의 몫이며 나와 상관없는 일이다.' },
  { index: 79, type: 1, value: null, question: '나는 조화로움을 추구하는 평화주의자이다.' },
  { index: 80, type: 8, value: null, question: '나는 정의감이 강하고 근면하다.' },
  { index: 81, type: 1, value: null, question: '나는 주로 나의 양심과 이성에 따른다.' },
]

export default questions
